# Set the window layout for the current tab
layout fat
# Set the working directory for windows in the current tab
cd ~/projects/grantmacken/dots
#launch nvim README.md
# -S "$HOME/.cache/nvim/session/xq"
# title dots

# new_tab dotfiles
# cd ~/projects/grantmacken/dots
# enbled_layouts tall, stack
# launch nvr -s "README.md"
# Set the current layout

