# ==============================================================================
# Podman User Configuration File (~/.config/containers/containers.conf)
# ==============================================================================

[engine]
# Use modern high-performance networking for rootless containers
rootless_networking = "pasta"

# Use zstd:chunked for faster builds, lazy pulls, and better compression
compression_format = "zstd:chunked"

# Number of seconds to wait before timing out an image pull
pull_policy = "missing"

# Clear systemd notification pathways to prevent logs spam on your host
env = [
  "NOTIFY_SOCKET=",
]
