
local _M = {}



--[[


--]]--



--[[
-

TOKENS as defined by xQuery3.1 grammer parser
token keywords and symbols found in expressions


Literal contents
and NAMES
and whitespace S

      "(0)",
      "IntegerLiteral",
      "DecimalLiteral",
      "DoubleLiteral",
      "StringLiteral",
      "URIQualifiedName",
      "PredefinedEntityRef",
      "'\"\"'",
      "EscapeApos",
      "ElementContentChar",
      "QuotAttrContentChar",
      "AposAttrContentChar",
      "PITarget",
      "CharRef",
      "NCName",
      "QName",
      "StringConstructorChars",
      "S",
      "S",
      "CommentContents",
      "PragmaContents",
      "Wildcard",
      "DirCommentContents",
      "DirPIContents",
      "CDataSectionContents",
      "EOF",

 
token symbols
     "'!'",
      "'!='",
      "'\"'",
      "'#'",
      "'#)'",
      "'$'",
      "'%'",
      "''''",
      "'('",
      "'(#'",
      "'(:'",
      "')'",
      "'*'",
      "'+'",
      "','",
      "'-'",
      "'-->'",
      "'.'",
      "'..'",
      "'/'",
      "'//'",
      "'/>'",
      "':'",
      "':)'",
      "'::'",
      "':='",
      "';'",
      "'<'",
      "'<!--'",
      "'<![CDATA['",
      "'</'",
      "'<<'",
      "'<='",
      "'<?'",
      "'='",
      "'=>'",
      "'>'",
      "'>='",
      "'>>'",
      "'?'",
      "'?>'",
      "'@'",
      "'NaN'",
      "'['",
      "']'",
      "'\]\]>'",
      "']``'",
      "'``['",
      "'`{'",


      "'{'",
      "'{{'",
      "'|'",
      "'||'",
      "'}'",
      "'}`'",
      "'}}'"
--]]

 _M.words = {
      'allowing',
      'ancestor',
      'ancestor-or-self',
      'and',
      'array',
      'as',
      'ascending',
      'at',
      'attribute',
      'base-uri',
      'boundary-space',
      'by',
      'case',
      'cast',
      'castable',
      'catch',
      'child',
      'collation',
      'comment',
      'construction',
      'context',
      'copy-namespaces',
      'count',
      'decimal-format',
      'decimal-separator',
      'declare',
      'default',
      'descendant',
      'descendant-or-self',
      'descending',
      'digit',
      'div',
      'document',
      'document-node',
      'element',
      'else',
      'empty',
      'empty-sequence',
      'encoding',
      'end',
      'eq',
      'every',
      'except',
      'exponent-separator',
      'external',
      'following',
      'following-sibling',
      'for',
      'function',
      'ge',
      'greatest',
      'group',
      'grouping-separator',
      'gt',
      'idiv',
      'if',
      'import',
      'in',
      'infinity',
      'inherit',
      'instance',
      'intersect',
      'is',
      'item',
      'lax',
      'le',
      'least',
      'let',
      'lt',
      'map',
      'minus-sign',
      'mod',
      'module',
      'namespace',
      'namespace-node',
      'ne',
      'next',
      'no-inherit',
      'no-preserve',
      'node',
      'of',
      'only',
      'option',
      'or',
      'order',
      'ordered',
      'ordering',
      'parent',
      'pattern-separator',
      'per-mille',
      'percent',
      'preceding',
      'preceding-sibling',
      'preserve',
      'previous',
      'processing-instruction',
      'return',
      'satisfies',
      'schema',
      'schema-attribute',
      'schema-element',
      'self',
      'sliding',
      'some',
      'stable',
      'start',
      'strict',
      'strip',
      'switch',
      'text',
      'then',
      'to',
      'treat',
      'try',
      'tumbling',
      'type',
      'typeswitch',
      'union',
      'unordered',
      'validate',
      'variable',
      'version',
      'when',
      'where',
      'window',
      'xquery',
      'zero-digit',
    }

return _M
